#!/usr/bin/env bash
# =============================================================================
# run_codechecker.sh
#
# PURPOSE:
#   Runs the thesis padding-leak checker over a real C project via CodeChecker
#   and collects two things:
#     1. A structured CSV event log (events.csv) — every boundary-transfer
#        event the checker extracted, whether or not it became a warning.
#        This is the raw data that populates Tables 8.1 and 8.2.
#     2. Timing measurements for baseline vs with-checker runs.
#        This populates Table 8.3 (performance overhead).
#
# USAGE:
#   ./scripts/run_codechecker.sh [PROJECT_DIR] [COMPILE_COMMANDS]
#
# EXAMPLES:
#   # Analyze zlib with explicit paths:
#   ./scripts/run_codechecker.sh ~/zlib ~/zlib/build/compile_commands.json
#
#   # Run with no arguments — falls back to demo/ as a smoke test:
#   ./scripts/run_codechecker.sh
#
# ENVIRONMENT VARIABLE OVERRIDES:
#   PLUGIN_PATH  — path to SecurityMiscPlugin.so  (default: build/SecurityMiscPlugin.so)
#   CC_RESULTS   — where CodeChecker writes results (default: ./cc-results)
#   EVENT_LOG    — where the checker writes CSV rows (default: ./events.csv)
# =============================================================================

set -euo pipefail
# set -e  : exit immediately if any command returns a non-zero exit code
# set -u  : treat unset variables as errors rather than silently using ""
# set -o pipefail : if a command in a pipeline fails, the whole pipeline fails

# Find the repo root regardless of where this script is called from.
# BASH_SOURCE[0] is the path to this script itself.
# dirname strips the filename leaving scripts/
# cd ../  moves up one level to the repo root
# pwd prints the absolute path
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# =============================================================================
# CONFIGURATION
# ${VAR:-default} means: use $VAR if set by the caller, otherwise use default.
# Positional arguments $1 and $2 let the caller specify project and compile db.
# =============================================================================
PLUGIN_PATH="${PLUGIN_PATH:-$ROOT/build/SecurityMiscPlugin.so}"
CC_RESULTS="${CC_RESULTS:-$ROOT/cc-results}"
EVENT_LOG="${EVENT_LOG:-$ROOT/events.csv}"
PROJECT_DIR="${1:-$ROOT/demo}"                             # $1 = first positional arg
COMPILE_COMMANDS="${2:-$ROOT/demo/compile_commands.json}" # $2 = second positional arg

# =============================================================================
# VALIDATION
# Fail fast with clear error messages before doing any analysis.
# Better to stop here than to fail 30 seconds into a CodeChecker run.
# =============================================================================

# Check the plugin .so has been built — if missing, build.sh hasn't been run.
if [[ ! -f "$PLUGIN_PATH" ]]; then
  echo "[ERROR] Plugin not found at: $PLUGIN_PATH"
  echo "        Run:  bash scripts/build.sh"
  exit 1
fi

# Check compile_commands.json exists for the target project.
# CodeChecker needs this to know which files to analyze and with what flags.
# Generated by cmake with -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
if [[ ! -f "$COMPILE_COMMANDS" ]]; then
  echo "[ERROR] compile_commands.json not found at: $COMPILE_COMMANDS"
  echo "        Generate with:  cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..."
  exit 1
fi

# Check CodeChecker is available in PATH.
# command -v prints the path if found; >/dev/null 2>&1 silences the output.
command -v CodeChecker >/dev/null 2>&1 || {
  echo "[ERROR] CodeChecker not found in PATH."
  echo "        Install: pip install codechecker"
  echo "        Or activate your venv: source ~/codechecker-env/bin/activate"
  exit 1
}

# =============================================================================
# EVENT LOG INITIALISATION
#
# The checker writes one CSV row per extracted boundary-transfer event to the
# file at $PADDING_LEAK_LOG. This gives us richer data than diagnostics alone —
# we can see events that were extracted but suppressed, which populates Nsup.
#
# We only write the header if the file does not already exist so that running
# this script against multiple projects appends all rows to one events.csv.
# =============================================================================
if [[ ! -f "$EVENT_LOG" ]]; then
  echo "boundary_fn,event_kind,type_name,has_padding,pad_bytes,init_class,evidence_level,diag_emitted" \
    > "$EVENT_LOG"
fi

# export makes PADDING_LEAK_LOG visible to child processes.
# Without export the variable exists in this shell but CodeChecker and the
# clang-tidy processes it spawns would not see it.
export PADDING_LEAK_LOG="$EVENT_LOG"

# =============================================================================
# STEP 1: BASELINE TIMING
#
# Run CodeChecker with all checks disabled to measure how long the toolchain
# takes without our checker. The overhead of our checker is:
#   overhead = checker_time - baseline_time
#
# We write the minimal clang-tidy flags to a temp file because CodeChecker
# 6.27.3 requires cc-verbatim-args-file to be a real file path.
# Process substitution <(echo ...) creates a virtual file descriptor, not a
# real path, so CodeChecker cannot open it — we use mktemp instead.
#
# date +%s%N gives nanoseconds since Unix epoch.
# (T1 - T0) / 1000000 converts nanoseconds to milliseconds.
# =============================================================================
echo "=== [1/3] Baseline analysis (no custom checker) ==="

BASELINE_ARGS_FILE=$(mktemp /tmp/tidy_baseline_XXXXXX.txt)
echo "-checks=-*,clang-diagnostic-*" > "$BASELINE_ARGS_FILE"

T0=$(date +%s%N)

CodeChecker analyze "$COMPILE_COMMANDS" \
  --analyzers clang-tidy \
  --analyzer-config "clang-tidy:cc-verbatim-args-file=$BASELINE_ARGS_FILE" \
  --output "$CC_RESULTS/baseline" \
  --jobs 4 \
  --quiet 2>/dev/null || true
  # || true prevents set -e from killing the script when CodeChecker exits
  # non-zero after finding issues — that is expected behaviour

T1=$(date +%s%N)
BASELINE_MS=$(( (T1 - T0) / 1000000 ))  # nanoseconds → milliseconds
echo "    Baseline: ${BASELINE_MS} ms"

rm -f "$BASELINE_ARGS_FILE"

# =============================================================================
# STEP 2: CHECKER ANALYSIS
#
# Same run but with our plugin loaded and our check enabled.
# -load SecurityMiscPlugin.so tells clang-tidy to dlopen the plugin before
# starting analysis. The plugin registers security-misc-padding-boundary-leak
# via the ClangTidyModuleRegistry static initialiser.
# =============================================================================
echo "=== [2/3] Analysis with padding-leak checker ==="

# Write the clang-tidy flags to a temp file.
# CodeChecker reads this file and passes its contents verbatim to every
# clang-tidy invocation without modification ("verbatim").
TIDY_ARGS_FILE=$(mktemp /tmp/tidy_args_XXXXXX.txt)
echo "-load $PLUGIN_PATH -checks=-*,security-misc-padding-boundary-leak" \
  > "$TIDY_ARGS_FILE"

T0=$(date +%s%N)

CodeChecker analyze "$COMPILE_COMMANDS" \
  --analyzers clang-tidy \
  --analyzer-config "clang-tidy:cc-verbatim-args-file=$TIDY_ARGS_FILE" \
  --output "$CC_RESULTS/with_checker" \
  --jobs 4

T1=$(date +%s%N)
CHECKER_MS=$(( (T1 - T0) / 1000000 ))
echo "    With checker: ${CHECKER_MS} ms"

rm -f "$TIDY_ARGS_FILE"

# Calculate overhead percentage.
# Bash cannot do floating point arithmetic — delegate to a Python one-liner.
OVERHEAD_PCT="N/A"
if [[ $BASELINE_MS -gt 0 ]]; then
  OVERHEAD_PCT=$(python3 -c "print(f'{100*($CHECKER_MS-$BASELINE_MS)/$BASELINE_MS:.1f}%')")
fi
echo "    Overhead: ${OVERHEAD_PCT}"

# =============================================================================
# STEP 3: PARSE RESULTS
#
# CodeChecker parse converts the raw plist analysis results into human-readable
# terminal output and machine-readable JSON.
# The JSON is what collect_metrics.py reads to cross-check against events.csv.
# =============================================================================
echo "=== [3/3] Parsing results ==="
mkdir -p "$CC_RESULTS/json"

# Export machine-readable JSON for collect_metrics.py
CodeChecker parse "$CC_RESULTS/with_checker" \
  --export json \
  --output "$CC_RESULTS/json/results.json" || true

# Print human-readable summary to terminal
CodeChecker parse "$CC_RESULTS/with_checker" || true

# =============================================================================
# SUMMARY
# Print all output paths and the exact collect_metrics.py command to run next,
# with --baseline-ms and --checker-ms already filled in from this run.
# =============================================================================
echo ""
echo "=== Run complete ==="
echo "  Baseline:     ${BASELINE_MS} ms"
echo "  With checker: ${CHECKER_MS} ms"
echo "  Overhead:     ${OVERHEAD_PCT}"
echo "  Event log:    $EVENT_LOG"
echo "  CC results:   $CC_RESULTS/with_checker"
echo "  JSON export:  $CC_RESULTS/json/results.json"
echo ""
echo "  Next step — collect metrics for thesis tables:"
echo "  python3 scripts/collect_metrics.py \\"
echo "    --project <name> \\"
echo "    --log $EVENT_LOG \\"
echo "    --cc $CC_RESULTS/json/results.json \\"
echo "    --baseline-ms $BASELINE_MS \\"
echo "    --checker-ms $CHECKER_MS"
